name: nlp1
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.10.14=0
  - click=7.1.2=py_0
  - cudatoolkit=11.3.1=ha36c431_9
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - jbig=2.1=h7f98852_2003
  - joblib=0.17.0=py_0
  - jpeg=9d=h36c2ea0_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.8=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - nltk=3.5=py_0
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - pip=21.2.4=pyhd8ed1ab_0
  - python=3.9.7=hf930737_3_cpython
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h46c0cb4_0
  - regex=2021.8.3=py39h7f8727e_0
  - setuptools=59.4.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tbb=2021.4.0=h4bd325d_1
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.1
    - cachetools==4.2.4
    - certifi==2021.10.8
    - charset-normalizer==2.0.9
    - cycler==0.11.0
    - fonttools==4.28.3
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multidict==5.2.0
    - oauthlib==3.1.1
    - pillow==8.0.1
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytorch-lightning==1.5.0
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.6.1
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - yarl==1.7.2
    - zipp==3.6.0
prefix: /home/jochemsoons/anaconda3/envs/nlp1
